# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: YWMwZTg5ZGJhMTJjOWNjNjUyOTAyNTY2MmFjOGY5ZGRhMDYwZGJkNDUyMmVmMmRkNmIxNDE2NGE5Nzc4ZjEwOTQ3MDZmZWIxNzczNzhkZjU0Nzc0ODIxZDA0ZDM4MDU2NWUxZWI3YjM0ZThhMmMyMWI4NzA4YmI2MTEzMjJhMmM=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
